version: "3.7"
services:
  queue-service:
    image: tixfactory/queue-service:latest
    container_name: queue-service
    environment:
      ApplicationApiKey: "" # ME: Put the TixFactory.Queue.Service ApiKey here!
      LoggingServiceHost: logging.services.tixfactory.systems
    networks:
      tix-factory:
        aliases:
          - tix-factory-queue-service
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"
    restart: always
networks:
  tix-factory:
    name: tix-factory
