name: TixFactory.Queue.Service

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Docker Image
      run: docker build --tag tixfactory/queue-service:latest ./Node/queue-service
    - name: Login to DockerHub
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    - name: Push Docker Image
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker push tixfactory/queue-service:latest
